name: ci-linux-x86_64.yaml

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update and install build tools
        run: sudo apt-get update && sudo apt-get install build-essential wget doxygen

      # Runs a set of commands using the runners shell
      - name: Download cmake
        run: wget https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-Linux-x86_64.tar.gz
        
      - name: Unpack cmake
        run: |
          tar xf cmake-3.19.2-Linux-x86_64.tar.gz
          mv cmake-3.19.2-Linux-x86_64 cmake

      - name: Configure proton-chess
        run: |
          mkdir build
          cd build
          ../cmake/bin/cmake .. -DBUILD_TYPE=Release

      - name: Build proton-chess
        run: |
          cd build
          ../cmake/bin/cmake --build . --target protonchess
 
      - name: Build tests
        run: |
          cd build
          ../cmake/bin/cmake --build . --target proton-chess-tests-all
          
      - name: Run tests
        run: |
          cd build
          ./fen-extensions-tests
          ./libprotonchess-tests
